'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection

Namespace FCX
	
	<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="AgapeConnect")>  _
	Partial Public Class FCXDataContext
		Inherits System.Data.Linq.DataContext
		
		Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub InsertFCX_API_FinBat(instance As FCX_API_FinBat)
    End Sub
    Partial Private Sub UpdateFCX_API_FinBat(instance As FCX_API_FinBat)
    End Sub
    Partial Private Sub DeleteFCX_API_FinBat(instance As FCX_API_FinBat)
    End Sub
    Partial Private Sub InsertFCX_API_FinTran(instance As FCX_API_FinTran)
    End Sub
    Partial Private Sub UpdateFCX_API_FinTran(instance As FCX_API_FinTran)
    End Sub
    Partial Private Sub DeleteFCX_API_FinTran(instance As FCX_API_FinTran)
    End Sub
    Partial Private Sub InsertFCX_API_Key(instance As FCX_API_Key)
    End Sub
    Partial Private Sub UpdateFCX_API_Key(instance As FCX_API_Key)
    End Sub
    Partial Private Sub DeleteFCX_API_Key(instance As FCX_API_Key)
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("SiteSqlServer").ConnectionString, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public ReadOnly Property FCX_API_FinBats() As System.Data.Linq.Table(Of FCX_API_FinBat)
			Get
				Return Me.GetTable(Of FCX_API_FinBat)
			End Get
		End Property
		
		Public ReadOnly Property FCX_API_FinTrans() As System.Data.Linq.Table(Of FCX_API_FinTran)
			Get
				Return Me.GetTable(Of FCX_API_FinTran)
			End Get
		End Property
		
		Public ReadOnly Property FCX_API_Keys() As System.Data.Linq.Table(Of FCX_API_Key)
			Get
				Return Me.GetTable(Of FCX_API_Key)
			End Get
		End Property
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.FCX_API_FinBat")>  _
	Partial Public Class FCX_API_FinBat
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _FinBatId As Long
		
		Private _DeveloperId As Integer
		
		Private _Ledger As String
		
		Private _Status As System.Nullable(Of Byte)
		
		Private _StatusDesc As String
		
		Private _Received As System.Nullable(Of Date)
		
		Private _Downloaded As System.Nullable(Of Date)
		
		Private _ITN_Sent As Boolean
		
		Private _UniqueBatchRef As String
		
		Private _Description As String
		
		Private _FCX_API_FinTrans As EntitySet(Of FCX_API_FinTran)
		
		Private _FCX_API_Key As EntityRef(Of FCX_API_Key)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnFinBatIdChanging(value As Long)
    End Sub
    Partial Private Sub OnFinBatIdChanged()
    End Sub
    Partial Private Sub OnDeveloperIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnDeveloperIdChanged()
    End Sub
    Partial Private Sub OnLedgerChanging(value As String)
    End Sub
    Partial Private Sub OnLedgerChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As System.Nullable(Of Byte))
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OnStatusDescChanging(value As String)
    End Sub
    Partial Private Sub OnStatusDescChanged()
    End Sub
    Partial Private Sub OnReceivedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnReceivedChanged()
    End Sub
    Partial Private Sub OnDownloadedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDownloadedChanged()
    End Sub
    Partial Private Sub OnITN_SentChanging(value As Boolean)
    End Sub
    Partial Private Sub OnITN_SentChanged()
    End Sub
    Partial Private Sub OnUniqueBatchRefChanging(value As String)
    End Sub
    Partial Private Sub OnUniqueBatchRefChanged()
    End Sub
    Partial Private Sub OnDescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnDescriptionChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			Me._FCX_API_FinTrans = New EntitySet(Of FCX_API_FinTran)(AddressOf Me.attach_FCX_API_FinTrans, AddressOf Me.detach_FCX_API_FinTrans)
			Me._FCX_API_Key = CType(Nothing, EntityRef(Of FCX_API_Key))
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FinBatId", AutoSync:=AutoSync.OnInsert, DbType:="BigInt NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
		Public Property FinBatId() As Long
			Get
				Return Me._FinBatId
			End Get
			Set
				If ((Me._FinBatId = value)  _
							= false) Then
					Me.OnFinBatIdChanging(value)
					Me.SendPropertyChanging
					Me._FinBatId = value
					Me.SendPropertyChanged("FinBatId")
					Me.OnFinBatIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DeveloperId", DbType:="Int NOT NULL")>  _
		Public Property DeveloperId() As Integer
			Get
				Return Me._DeveloperId
			End Get
			Set
				If ((Me._DeveloperId = value)  _
							= false) Then
					If Me._FCX_API_Key.HasLoadedOrAssignedValue Then
						Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
					End If
					Me.OnDeveloperIdChanging(value)
					Me.SendPropertyChanging
					Me._DeveloperId = value
					Me.SendPropertyChanged("DeveloperId")
					Me.OnDeveloperIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Ledger", DbType:="NVarChar(10)")>  _
		Public Property Ledger() As String
			Get
				Return Me._Ledger
			End Get
			Set
				If (String.Equals(Me._Ledger, value) = false) Then
					Me.OnLedgerChanging(value)
					Me.SendPropertyChanging
					Me._Ledger = value
					Me.SendPropertyChanged("Ledger")
					Me.OnLedgerChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="TinyInt")>  _
		Public Property Status() As System.Nullable(Of Byte)
			Get
				Return Me._Status
			End Get
			Set
				If (Me._Status.Equals(value) = false) Then
					Me.OnStatusChanging(value)
					Me.SendPropertyChanging
					Me._Status = value
					Me.SendPropertyChanged("Status")
					Me.OnStatusChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StatusDesc", DbType:="VarChar(MAX)")>  _
		Public Property StatusDesc() As String
			Get
				Return Me._StatusDesc
			End Get
			Set
				If (String.Equals(Me._StatusDesc, value) = false) Then
					Me.OnStatusDescChanging(value)
					Me.SendPropertyChanging
					Me._StatusDesc = value
					Me.SendPropertyChanged("StatusDesc")
					Me.OnStatusDescChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Received", DbType:="DateTime")>  _
		Public Property Received() As System.Nullable(Of Date)
			Get
				Return Me._Received
			End Get
			Set
				If (Me._Received.Equals(value) = false) Then
					Me.OnReceivedChanging(value)
					Me.SendPropertyChanging
					Me._Received = value
					Me.SendPropertyChanged("Received")
					Me.OnReceivedChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Downloaded", DbType:="DateTime")>  _
		Public Property Downloaded() As System.Nullable(Of Date)
			Get
				Return Me._Downloaded
			End Get
			Set
				If (Me._Downloaded.Equals(value) = false) Then
					Me.OnDownloadedChanging(value)
					Me.SendPropertyChanging
					Me._Downloaded = value
					Me.SendPropertyChanged("Downloaded")
					Me.OnDownloadedChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITN_Sent", DbType:="Bit NOT NULL")>  _
		Public Property ITN_Sent() As Boolean
			Get
				Return Me._ITN_Sent
			End Get
			Set
				If ((Me._ITN_Sent = value)  _
							= false) Then
					Me.OnITN_SentChanging(value)
					Me.SendPropertyChanging
					Me._ITN_Sent = value
					Me.SendPropertyChanged("ITN_Sent")
					Me.OnITN_SentChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UniqueBatchRef", DbType:="NVarChar(200) NOT NULL", CanBeNull:=false)>  _
		Public Property UniqueBatchRef() As String
			Get
				Return Me._UniqueBatchRef
			End Get
			Set
				If (String.Equals(Me._UniqueBatchRef, value) = false) Then
					Me.OnUniqueBatchRefChanging(value)
					Me.SendPropertyChanging
					Me._UniqueBatchRef = value
					Me.SendPropertyChanged("UniqueBatchRef")
					Me.OnUniqueBatchRefChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Description", DbType:="NVarChar(200)")>  _
		Public Property Description() As String
			Get
				Return Me._Description
			End Get
			Set
				If (String.Equals(Me._Description, value) = false) Then
					Me.OnDescriptionChanging(value)
					Me.SendPropertyChanging
					Me._Description = value
					Me.SendPropertyChanged("Description")
					Me.OnDescriptionChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="FCX_API_FinBat_FCX_API_FinTran", Storage:="_FCX_API_FinTrans", ThisKey:="FinBatId", OtherKey:="FinBatId")>  _
		Public Property FCX_API_FinTrans() As EntitySet(Of FCX_API_FinTran)
			Get
				Return Me._FCX_API_FinTrans
			End Get
			Set
				Me._FCX_API_FinTrans.Assign(value)
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="FCX_API_Key_FCX_API_FinBat", Storage:="_FCX_API_Key", ThisKey:="DeveloperId", OtherKey:="DeveloperId", IsForeignKey:=true)>  _
		Public Property FCX_API_Key() As FCX_API_Key
			Get
				Return Me._FCX_API_Key.Entity
			End Get
			Set
				Dim previousValue As FCX_API_Key = Me._FCX_API_Key.Entity
				If ((Object.Equals(previousValue, value) = false)  _
							OrElse (Me._FCX_API_Key.HasLoadedOrAssignedValue = false)) Then
					Me.SendPropertyChanging
					If ((previousValue Is Nothing)  _
								= false) Then
						Me._FCX_API_Key.Entity = Nothing
						previousValue.FCX_API_FinBats.Remove(Me)
					End If
					Me._FCX_API_Key.Entity = value
					If ((value Is Nothing)  _
								= false) Then
						value.FCX_API_FinBats.Add(Me)
						Me._DeveloperId = value.DeveloperId
					Else
						Me._DeveloperId = CType(Nothing, Integer)
					End If
					Me.SendPropertyChanged("FCX_API_Key")
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
		
		Private Sub attach_FCX_API_FinTrans(ByVal entity As FCX_API_FinTran)
			Me.SendPropertyChanging
			entity.FCX_API_FinBat = Me
		End Sub
		
		Private Sub detach_FCX_API_FinTrans(ByVal entity As FCX_API_FinTran)
			Me.SendPropertyChanging
			entity.FCX_API_FinBat = Nothing
		End Sub
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.FCX_API_FinTrans")>  _
	Partial Public Class FCX_API_FinTran
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _FinTransId As Long
		
		Private _Account As String
		
		Private _R_C As String
		
		Private _Amount As Decimal
		
		Private _Description As String
		
		Private _TrxDate As Date
		
		Private _Month As System.Nullable(Of Byte)
		
		Private _Year As System.Nullable(Of Short)
		
		Private _FinBatId As Long
		
		Private _UniqueTrxRef As String
		
		Private _FCX_API_FinBat As EntityRef(Of FCX_API_FinBat)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnFinTransIdChanging(value As Long)
    End Sub
    Partial Private Sub OnFinTransIdChanged()
    End Sub
    Partial Private Sub OnAccountChanging(value As String)
    End Sub
    Partial Private Sub OnAccountChanged()
    End Sub
    Partial Private Sub OnR_CChanging(value As String)
    End Sub
    Partial Private Sub OnR_CChanged()
    End Sub
    Partial Private Sub OnAmountChanging(value As Decimal)
    End Sub
    Partial Private Sub OnAmountChanged()
    End Sub
    Partial Private Sub OnDescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnDescriptionChanged()
    End Sub
    Partial Private Sub OnTrxDateChanging(value As Date)
    End Sub
    Partial Private Sub OnTrxDateChanged()
    End Sub
    Partial Private Sub OnMonthChanging(value As System.Nullable(Of Byte))
    End Sub
    Partial Private Sub OnMonthChanged()
    End Sub
    Partial Private Sub OnYearChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnYearChanged()
    End Sub
    Partial Private Sub OnFinBatIdChanging(value As Long)
    End Sub
    Partial Private Sub OnFinBatIdChanged()
    End Sub
    Partial Private Sub OnUniqueTrxRefChanging(value As String)
    End Sub
    Partial Private Sub OnUniqueTrxRefChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			Me._FCX_API_FinBat = CType(Nothing, EntityRef(Of FCX_API_FinBat))
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FinTransId", AutoSync:=AutoSync.OnInsert, DbType:="BigInt NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
		Public Property FinTransId() As Long
			Get
				Return Me._FinTransId
			End Get
			Set
				If ((Me._FinTransId = value)  _
							= false) Then
					Me.OnFinTransIdChanging(value)
					Me.SendPropertyChanging
					Me._FinTransId = value
					Me.SendPropertyChanged("FinTransId")
					Me.OnFinTransIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Account", DbType:="NVarChar(20) NOT NULL", CanBeNull:=false)>  _
		Public Property Account() As String
			Get
				Return Me._Account
			End Get
			Set
				If (String.Equals(Me._Account, value) = false) Then
					Me.OnAccountChanging(value)
					Me.SendPropertyChanging
					Me._Account = value
					Me.SendPropertyChanged("Account")
					Me.OnAccountChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[R/C]", Storage:="_R_C", DbType:="NVarChar(20) NOT NULL", CanBeNull:=false)>  _
		Public Property R_C() As String
			Get
				Return Me._R_C
			End Get
			Set
				If (String.Equals(Me._R_C, value) = false) Then
					Me.OnR_CChanging(value)
					Me.SendPropertyChanging
					Me._R_C = value
					Me.SendPropertyChanged("R_C")
					Me.OnR_CChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Amount", DbType:="Money NOT NULL")>  _
		Public Property Amount() As Decimal
			Get
				Return Me._Amount
			End Get
			Set
				If ((Me._Amount = value)  _
							= false) Then
					Me.OnAmountChanging(value)
					Me.SendPropertyChanging
					Me._Amount = value
					Me.SendPropertyChanged("Amount")
					Me.OnAmountChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Description", DbType:="NVarChar(120) NOT NULL", CanBeNull:=false)>  _
		Public Property Description() As String
			Get
				Return Me._Description
			End Get
			Set
				If (String.Equals(Me._Description, value) = false) Then
					Me.OnDescriptionChanging(value)
					Me.SendPropertyChanging
					Me._Description = value
					Me.SendPropertyChanged("Description")
					Me.OnDescriptionChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TrxDate", DbType:="DateTime NOT NULL")>  _
		Public Property TrxDate() As Date
			Get
				Return Me._TrxDate
			End Get
			Set
				If ((Me._TrxDate = value)  _
							= false) Then
					Me.OnTrxDateChanging(value)
					Me.SendPropertyChanging
					Me._TrxDate = value
					Me.SendPropertyChanged("TrxDate")
					Me.OnTrxDateChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Month", DbType:="TinyInt")>  _
		Public Property Month() As System.Nullable(Of Byte)
			Get
				Return Me._Month
			End Get
			Set
				If (Me._Month.Equals(value) = false) Then
					Me.OnMonthChanging(value)
					Me.SendPropertyChanging
					Me._Month = value
					Me.SendPropertyChanged("Month")
					Me.OnMonthChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Year", DbType:="SmallInt")>  _
		Public Property Year() As System.Nullable(Of Short)
			Get
				Return Me._Year
			End Get
			Set
				If (Me._Year.Equals(value) = false) Then
					Me.OnYearChanging(value)
					Me.SendPropertyChanging
					Me._Year = value
					Me.SendPropertyChanged("Year")
					Me.OnYearChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FinBatId", DbType:="BigInt NOT NULL")>  _
		Public Property FinBatId() As Long
			Get
				Return Me._FinBatId
			End Get
			Set
				If ((Me._FinBatId = value)  _
							= false) Then
					If Me._FCX_API_FinBat.HasLoadedOrAssignedValue Then
						Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
					End If
					Me.OnFinBatIdChanging(value)
					Me.SendPropertyChanging
					Me._FinBatId = value
					Me.SendPropertyChanged("FinBatId")
					Me.OnFinBatIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UniqueTrxRef", DbType:="VarChar(200) NOT NULL", CanBeNull:=false)>  _
		Public Property UniqueTrxRef() As String
			Get
				Return Me._UniqueTrxRef
			End Get
			Set
				If (String.Equals(Me._UniqueTrxRef, value) = false) Then
					Me.OnUniqueTrxRefChanging(value)
					Me.SendPropertyChanging
					Me._UniqueTrxRef = value
					Me.SendPropertyChanged("UniqueTrxRef")
					Me.OnUniqueTrxRefChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="FCX_API_FinBat_FCX_API_FinTran", Storage:="_FCX_API_FinBat", ThisKey:="FinBatId", OtherKey:="FinBatId", IsForeignKey:=true)>  _
		Public Property FCX_API_FinBat() As FCX_API_FinBat
			Get
				Return Me._FCX_API_FinBat.Entity
			End Get
			Set
				Dim previousValue As FCX_API_FinBat = Me._FCX_API_FinBat.Entity
				If ((Object.Equals(previousValue, value) = false)  _
							OrElse (Me._FCX_API_FinBat.HasLoadedOrAssignedValue = false)) Then
					Me.SendPropertyChanging
					If ((previousValue Is Nothing)  _
								= false) Then
						Me._FCX_API_FinBat.Entity = Nothing
						previousValue.FCX_API_FinTrans.Remove(Me)
					End If
					Me._FCX_API_FinBat.Entity = value
					If ((value Is Nothing)  _
								= false) Then
						value.FCX_API_FinTrans.Add(Me)
						Me._FinBatId = value.FinBatId
					Else
						Me._FinBatId = CType(Nothing, Long)
					End If
					Me.SendPropertyChanged("FCX_API_FinBat")
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
	
	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.FCX_API_Keys")>  _
	Partial Public Class FCX_API_Key
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _DeveloperId As Integer
		
		Private _API_KEY As System.Guid
		
		Private _FirstName As String
		
		Private _LastName As String
		
		Private _ProductName As String
		
		Private _ITN As String
		
		Private _WhiteList As String
		
		Private _TrustLevel As Byte
		
		Private _Notes As String
		
		Private _Active As Boolean
		
		Private _PortalId As Integer
		
		Private _FCX_API_FinBats As EntitySet(Of FCX_API_FinBat)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnDeveloperIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnDeveloperIdChanged()
    End Sub
    Partial Private Sub OnAPI_KEYChanging(value As System.Guid)
    End Sub
    Partial Private Sub OnAPI_KEYChanged()
    End Sub
    Partial Private Sub OnFirstNameChanging(value As String)
    End Sub
    Partial Private Sub OnFirstNameChanged()
    End Sub
    Partial Private Sub OnLastNameChanging(value As String)
    End Sub
    Partial Private Sub OnLastNameChanged()
    End Sub
    Partial Private Sub OnProductNameChanging(value As String)
    End Sub
    Partial Private Sub OnProductNameChanged()
    End Sub
    Partial Private Sub OnITNChanging(value As String)
    End Sub
    Partial Private Sub OnITNChanged()
    End Sub
    Partial Private Sub OnWhiteListChanging(value As String)
    End Sub
    Partial Private Sub OnWhiteListChanged()
    End Sub
    Partial Private Sub OnTrustLevelChanging(value As Byte)
    End Sub
    Partial Private Sub OnTrustLevelChanged()
    End Sub
    Partial Private Sub OnNotesChanging(value As String)
    End Sub
    Partial Private Sub OnNotesChanged()
    End Sub
    Partial Private Sub OnActiveChanging(value As Boolean)
    End Sub
    Partial Private Sub OnActiveChanged()
    End Sub
    Partial Private Sub OnPortalIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnPortalIdChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			Me._FCX_API_FinBats = New EntitySet(Of FCX_API_FinBat)(AddressOf Me.attach_FCX_API_FinBats, AddressOf Me.detach_FCX_API_FinBats)
			OnCreated
		End Sub
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DeveloperId", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
		Public Property DeveloperId() As Integer
			Get
				Return Me._DeveloperId
			End Get
			Set
				If ((Me._DeveloperId = value)  _
							= false) Then
					Me.OnDeveloperIdChanging(value)
					Me.SendPropertyChanging
					Me._DeveloperId = value
					Me.SendPropertyChanged("DeveloperId")
					Me.OnDeveloperIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[API-KEY]", Storage:="_API_KEY", DbType:="UniqueIdentifier NOT NULL")>  _
		Public Property API_KEY() As System.Guid
			Get
				Return Me._API_KEY
			End Get
			Set
				If ((Me._API_KEY = value)  _
							= false) Then
					Me.OnAPI_KEYChanging(value)
					Me.SendPropertyChanging
					Me._API_KEY = value
					Me.SendPropertyChanged("API_KEY")
					Me.OnAPI_KEYChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FirstName", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
		Public Property FirstName() As String
			Get
				Return Me._FirstName
			End Get
			Set
				If (String.Equals(Me._FirstName, value) = false) Then
					Me.OnFirstNameChanging(value)
					Me.SendPropertyChanging
					Me._FirstName = value
					Me.SendPropertyChanged("FirstName")
					Me.OnFirstNameChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastName", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
		Public Property LastName() As String
			Get
				Return Me._LastName
			End Get
			Set
				If (String.Equals(Me._LastName, value) = false) Then
					Me.OnLastNameChanging(value)
					Me.SendPropertyChanging
					Me._LastName = value
					Me.SendPropertyChanged("LastName")
					Me.OnLastNameChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProductName", DbType:="NVarChar(50)")>  _
		Public Property ProductName() As String
			Get
				Return Me._ProductName
			End Get
			Set
				If (String.Equals(Me._ProductName, value) = false) Then
					Me.OnProductNameChanging(value)
					Me.SendPropertyChanging
					Me._ProductName = value
					Me.SendPropertyChanged("ProductName")
					Me.OnProductNameChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ITN", DbType:="NVarChar(300)")>  _
		Public Property ITN() As String
			Get
				Return Me._ITN
			End Get
			Set
				If (String.Equals(Me._ITN, value) = false) Then
					Me.OnITNChanging(value)
					Me.SendPropertyChanging
					Me._ITN = value
					Me.SendPropertyChanged("ITN")
					Me.OnITNChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WhiteList", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
		Public Property WhiteList() As String
			Get
				Return Me._WhiteList
			End Get
			Set
				If (String.Equals(Me._WhiteList, value) = false) Then
					Me.OnWhiteListChanging(value)
					Me.SendPropertyChanging
					Me._WhiteList = value
					Me.SendPropertyChanged("WhiteList")
					Me.OnWhiteListChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TrustLevel", DbType:="TinyInt NOT NULL")>  _
		Public Property TrustLevel() As Byte
			Get
				Return Me._TrustLevel
			End Get
			Set
				If ((Me._TrustLevel = value)  _
							= false) Then
					Me.OnTrustLevelChanging(value)
					Me.SendPropertyChanging
					Me._TrustLevel = value
					Me.SendPropertyChanged("TrustLevel")
					Me.OnTrustLevelChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Notes", DbType:="NVarChar(MAX)")>  _
		Public Property Notes() As String
			Get
				Return Me._Notes
			End Get
			Set
				If (String.Equals(Me._Notes, value) = false) Then
					Me.OnNotesChanging(value)
					Me.SendPropertyChanging
					Me._Notes = value
					Me.SendPropertyChanged("Notes")
					Me.OnNotesChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Active", DbType:="Bit NOT NULL")>  _
		Public Property Active() As Boolean
			Get
				Return Me._Active
			End Get
			Set
				If ((Me._Active = value)  _
							= false) Then
					Me.OnActiveChanging(value)
					Me.SendPropertyChanging
					Me._Active = value
					Me.SendPropertyChanged("Active")
					Me.OnActiveChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PortalId", DbType:="Int NOT NULL")>  _
		Public Property PortalId() As Integer
			Get
				Return Me._PortalId
			End Get
			Set
				If ((Me._PortalId = value)  _
							= false) Then
					Me.OnPortalIdChanging(value)
					Me.SendPropertyChanging
					Me._PortalId = value
					Me.SendPropertyChanged("PortalId")
					Me.OnPortalIdChanged
				End If
			End Set
		End Property
		
		<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="FCX_API_Key_FCX_API_FinBat", Storage:="_FCX_API_FinBats", ThisKey:="DeveloperId", OtherKey:="DeveloperId")>  _
		Public Property FCX_API_FinBats() As EntitySet(Of FCX_API_FinBat)
			Get
				Return Me._FCX_API_FinBats
			End Get
			Set
				Me._FCX_API_FinBats.Assign(value)
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
		
		Private Sub attach_FCX_API_FinBats(ByVal entity As FCX_API_FinBat)
			Me.SendPropertyChanging
			entity.FCX_API_Key = Me
		End Sub
		
		Private Sub detach_FCX_API_FinBats(ByVal entity As FCX_API_FinBat)
			Me.SendPropertyChanging
			entity.FCX_API_Key = Nothing
		End Sub
	End Class
End Namespace
