
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("cfd8cccb-337c-4087-b2c0-d5a5a0d8101e")>
Namespace Account

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class DataserverPortalUsersEntities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new DataserverPortalUsersEntities object using the connection string found in the 'DataserverPortalUsersEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=DataserverPortalUsersEntities", "DataserverPortalUsersEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new DataserverPortalUsersEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "DataserverPortalUsersEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new DataserverPortalUsersEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "DataserverPortalUsersEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property DataserverUserPortal() As ObjectSet(Of DataserverUserPortal)
            Get
                If (_DataserverUserPortal Is Nothing) Then
                    _DataserverUserPortal = MyBase.CreateObjectSet(Of DataserverUserPortal)("DataserverUserPortal")
                End If
                Return _DataserverUserPortal
            End Get
        End Property
    
        Private _DataserverUserPortal As ObjectSet(Of DataserverUserPortal)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the DataserverUserPortal EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToDataserverUserPortal(ByVal dataserverUserPortal As DataserverUserPortal)
            MyBase.AddObject("DataserverUserPortal", dataserverUserPortal)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="DataserverPortalUsersEntitiesModel", Name:="DataserverUserPortal")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class DataserverUserPortal
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new DataserverUserPortal object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="ssoCode">Initial value of the SsoCode property.</param>
        Public Shared Function CreateDataserverUserPortal(id As Global.System.Guid, ssoCode As Global.System.Guid) As DataserverUserPortal
            Dim dataserverUserPortal as DataserverUserPortal = New DataserverUserPortal
            dataserverUserPortal.Id = id
            dataserverUserPortal.SsoCode = ssoCode
            Return dataserverUserPortal
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Guid
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Guid
        Private Partial Sub OnIdChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property SsoCode() As Global.System.Guid
            Get
                Return _SsoCode
            End Get
            Set
                OnSsoCodeChanging(value)
                ReportPropertyChanging("SsoCode")
                _SsoCode = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SsoCode")
                OnSsoCodeChanged()
            End Set
        End Property
    
        Private _SsoCode As Global.System.Guid
        Private Partial Sub OnSsoCodeChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnSsoCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property PortalUri() As Global.System.String
            Get
                Return _PortalUri
            End Get
            Set
                OnPortalUriChanging(value)
                ReportPropertyChanging("PortalUri")
                _PortalUri = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("PortalUri")
                OnPortalUriChanged()
            End Set
        End Property
    
        Private _PortalUri As Global.System.String
        Private Partial Sub OnPortalUriChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPortalUriChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property PortalName() As Global.System.String
            Get
                Return _PortalName
            End Get
            Set
                OnPortalNameChanging(value)
                ReportPropertyChanging("PortalName")
                _PortalName = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("PortalName")
                OnPortalNameChanged()
            End Set
        End Property
    
        Private _PortalName As Global.System.String
        Private Partial Sub OnPortalNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPortalNameChanged()
        End Sub

        #End Region

    End Class

    #End Region

    
End Namespace
