<?xml version="1.0" encoding="utf-8"?><Database Name="AC-FR" Class="CartDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=AC-FR;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SiteSqlServer" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FR_Cart" Member="FR_Carts">
    <Type Name="FR_Cart">
      <Column Name="CartID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnonID" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="PayMethod" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="TransLog" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MerchantFee" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CreditFee" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserComments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StaffComments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrderState" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ShipCost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DeliveryInst" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PortalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShipAddressBookID" Storage="_ShipDetailsID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ShipCompany" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipReference" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreditNote" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShipVAT" Type="System.Double" DbType="money" CanBeNull="true" />
      <Column Name="BillAddressBookID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="FR_Cart_FR_Cart_Content" Member="FR_Cart_Contents" ThisKey="CartID" OtherKey="CartID" Type="FR_Cart_Content" />
    </Type>
  </Table>
  <Table Name="dbo.FR_Donations" Member="FR_Donations">
    <Type Name="FR_Donations">
      <Column Name="DonationID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CartContentID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DestinationType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DestinationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="nvarchar(max)" CanBeNull="true" />
      <Association Name="FR_Cart_Content_FR_Donations" Member="FR_Cart_Content" ThisKey="CartContentID" OtherKey="CartContentID" Type="FR_Cart_Content" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FR_Cart_Content" Member="FR_Cart_Contents">
    <Type Name="FR_Cart_Content">
      <Column Name="CartContentID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CartID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ItemType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ItemRef" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Cost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Tax" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DiscountAmt" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DiscountPercent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Dispatchable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="FR_Cart_Content_FR_Donations" Member="FR_Donations" ThisKey="CartContentID" OtherKey="CartContentID" Type="FR_Donations" Cardinality="One" />
      <Association Name="FR_Cart_FR_Cart_Content" Member="FR_Cart" ThisKey="CartID" OtherKey="CartID" Type="FR_Cart" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FR_Cart_AddressBook" Member="FR_Cart_AddressBook">
    <Type Name="FR_Cart_AddressBook">
      <Column Name="AddressBookID" Storage="_ShipDetailsID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>